site_name: DGMJR-Actions
site_author: David G. Moore, Jr.
site_url: https://dgmjr-actions.docs.dgmjr.io/
site_description: All of my Git Hub actions!
copyright: © 2022 - 2023 David G. Moore, Jr., All rights reserved
dev_addr: "127.0.0.1:8000"
docs_dir: ../docs
site_dir: ../site
theme: 
  name: material
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  custom_dir: overrides
extra_css: 
  - stylesheets/extra.css
xmarkdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        permalink: True
        separator: "_"
    - codehilite
    - footnotes
    - smarty
    - sane_lists